"%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKEpp_CHEMKIN_PreProcessor.exe" --input input.dic.POLIMI_BIOGASOLINE_REDUCED171R_1410

"%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKEpp_CHEMKIN_PreProcessor.exe" --input input.dic.POLIMI_DIESEL_BIODIESEL_REDUCED226_1410

"%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKEpp_CHEMKIN_PreProcessor.exe" --input input.dic.POLIMI_DIESEL_REDUCED201C_1410

"%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKEpp_CHEMKIN_PreProcessor.exe" --input input.dic.POLIMI_FAME_REDUCED177_1410

"%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKEpp_CHEMKIN_PreProcessor.exe" --input input.dic.POLIMI_GASOLINE_REDUCED156R_1410

"%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKEpp_CHEMKIN_PreProcessor.exe" --input input.dic.POLIMI_KEROSENE_LTHT_REDUCED231_1410

"%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKEpp_CHEMKIN_PreProcessor.exe" --input input.dic.POLIMI_KEROSENE_REDUCED121_1410

"%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKEpp_CHEMKIN_PreProcessor.exe" --input input.dic.POLIMI_NC7_REDUCED106_1410

"%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKEpp_CHEMKIN_PreProcessor.exe" --input input.dic.POLIMI_NC12_REDUCED130_1410

pause
