%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_BIO1412

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_C1C3HT_1412

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_C1C3HT_NOX_1412

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_C1C3LT_1412

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_H2CO_1412

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_H2CO_NOX_1412

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_PRF_PAH_HT_1412

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_PRF_PAH_LT_1412

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_TOT_1412

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_TOT_NOX_1412

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.PRF_PAH_ALCOHOLS_ETHERS_HT_1412

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.PRF_PAH_ALCOHOLS_ETHERS_LT_1412

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.PRF_PAH_RFUELS_HT_1412

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.PRF_PAH_RFUELS_LT_1412

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.PRF_PAH_RFUELS_MESTERS_LT_1412

pause