%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_BIOGASOLINE_171R

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_DIESEL_201C

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_DIESEL_BIODIESEL_226

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_FAME_177

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_GASOLINE_156R

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_KEROSENE_121

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_KEROSENE_LTHT_231

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_NC7_106

%OPENSMOKEPP_EXE_FOLDER%\OpenSMOKE_CHEMKIN_PreProcessor.exe --input input.dic.POLIMI_NC12_130

pause